### ISSUE TITLE
[FEATURE] Start Conditions

### ISSUE THREAD

**Issue by JodieM** [toddhalfpenny/sfflowvisualiser-vscode#3]
I would like to see Start Conditions, Criteria of decisions etc. Not sure how that would be shown in the Mermaid but maybe in a table below the diagram.

**Comment by toddhalfpenny** [comment]
Yup, me too... this one is already on the list :)

**Comment by toddhalfpenny** [comment]
I might actually split this into multiple tickets... we'll leave this one for start conditions

**Comment by toddhalfpenny** [comment]
Fixed as part of v.0.2.2
