### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by msteinercrmfirm** [toddhalfpenny/sfflowvisualiser-vscode#5]
How do you use this instruction?  I've installed it.  Opened a flow, but I'm not seeing anything different in the interface?  How do you open the visual view or where are the mid files?

**Comment by mvogelgesang** [comment]
@msteinercrmfirm I was running into the same thing. In command palette, type `Flow Visualizer: Mermaid` and a preview will open a new tab along with a markdown file

**Comment by msteinercrmfirm** [comment]
Very cool.  Thank you!   Would recommend that gets added to the readme.
________________________________

**Comment by toddhalfpenny** [comment]
Fixed as part of v.0.2.2
