### ISSUE TITLE
Bug on loop graph

### ISSUE THREAD

**Issue by Manu2pace** [toddhalfpenny/sfflowvisualiser-vscode#8]
Hi thank you fo your great work.
I tested your extension on a flow of mine and I have a nasty bug on the attached flow : 
[maintenancePlan_tempsMoyenEntretien.flow-meta.xml.txt](https://github.com/toddhalfpenny/sfflowvisualiser-vscode/files/13349754/maintenancePlan_tempsMoyenEntretien.flow-meta.xml.txt)

it generate the following md : 

> X1_site --> loop_Sites_opp
> loop_Sites_opp --> X1_site
> loop_Sites_opp ---> END
> get_opportunity --> get_sites_opportunite
> get_sites_opportunite --> loop_Sites_opp
> update_maintenace_plan --> END
> START(( START )) --> get_opportunity

where it should generate this instead 
> X1_site --> loop_Sites_opp
> loop_Sites_opp --> X1_site
> loop_Sites_opp ---> update_maintenace_plan
> get_opportunity --> get_sites_opportunite
> get_sites_opportunite --> loop_Sites_opp
> update_maintenace_plan --> END
> START(( START )) --> get_opportunity

**Comment by toddhalfpenny** [comment]
Thanks @Manu2pace .
Are you also able to share a screenshot of the Fow as seen in the Salesforce org, please?

**Comment by Manu2pace** [comment]
Here it is from Salesforce : 
![Capture d’écran 2023-11-15 à 09 17 50](https://github.com/toddhalfpenny/sfflowvisualiser-vscode/assets/116733084/ec0258e5-be6c-4ee4-8db8-33fea94327ff)


dans in VScode as it is generated in markdown + flow <img width="1179" alt="Capture d’écran 2023-11-15 à 09 16 02" src="https://github.com/toddhalfpenny/sfflowvisualiser-vscode/assets/116733084/2046b055-8f75-4764-8d91-2177859f8038">
and what it should be based on the flow 
<img width="1008" alt="Capture d’écran 2023-11-15 à 09 15 40" src="https://github.com/toddhalfpenny/sfflowvisualiser-vscode/assets/116733084/b2e58f57-670b-48f0-b463-e5e28d86ba6f">

**Comment by toddhalfpenny** [comment]
Ah amazing! Thank you

**Comment by toddhalfpenny** [comment]
Should be fixed in #11
