### ISSUE TITLE
Include source for salesforce-flow-visualiser

### ISSUE THREAD

**Issue by ChuckJonas** [toddhalfpenny/sfflowvisualiser-vscode#9]
Seems like the bulk of the work being done in this package is happening in a file called `salesforce-flow-visualiser` that isn't included in the source.  

Are there any plans to open source this?  Would be nice to be able to contribute to bug fixes or use this in other projects (depending on the license).

Thanks

**Comment by toddhalfpenny** [comment]
Oh yes... on this version that is the case.
The next version brings some more out, though that lib is still needed.

And yes, the plan is indeed to open up the lib and have it on npm so it be used in other things (like DX CLI plugins, etc).
